[tool.ruff]

select = ["ALL"]

ignore = [
    "D", # Ignore docstrings
    "E501", # Line too long, let Black handle this
    "ANN", # typing, let mypy handle tis
    "INP001", # Namespace package eeeeh
    "PLR0913", #Too many args to func call
    "DTZ005", # datetime object without "tz" is not allowed
]

line-length = 120

[tool.black]

line-length = 120